#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="manodisha_db")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_adminuser(tbl_adminuser instance);
  partial void Updatetbl_adminuser(tbl_adminuser instance);
  partial void Deletetbl_adminuser(tbl_adminuser instance);
  partial void Inserttbl_Activity(tbl_Activity instance);
  partial void Updatetbl_Activity(tbl_Activity instance);
  partial void Deletetbl_Activity(tbl_Activity instance);
  partial void Inserttbl_press(tbl_press instance);
  partial void Updatetbl_press(tbl_press instance);
  partial void Deletetbl_press(tbl_press instance);
  partial void Inserttbl_event(tbl_event instance);
  partial void Updatetbl_event(tbl_event instance);
  partial void Deletetbl_event(tbl_event instance);
  partial void Inserttbl_gallery(tbl_gallery instance);
  partial void Updatetbl_gallery(tbl_gallery instance);
  partial void Deletetbl_gallery(tbl_gallery instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["manodisha_dbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_adminuser> tbl_adminusers
	{
		get
		{
			return this.GetTable<tbl_adminuser>();
		}
	}
	
	public System.Data.Linq.Table<tbl_Activity> tbl_Activities
	{
		get
		{
			return this.GetTable<tbl_Activity>();
		}
	}
	
	public System.Data.Linq.Table<tbl_press> tbl_presses
	{
		get
		{
			return this.GetTable<tbl_press>();
		}
	}
	
	public System.Data.Linq.Table<tbl_event> tbl_events
	{
		get
		{
			return this.GetTable<tbl_event>();
		}
	}
	
	public System.Data.Linq.Table<tbl_gallery> tbl_galleries
	{
		get
		{
			return this.GetTable<tbl_gallery>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_aed_adminuser")]
	public int USP_aed_adminuser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Decimal(18,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pwd", DbType="NVarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnterBy", DbType="NVarChar(50)")] string enterBy)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, id, name, pwd, enterBy);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_aed_Activity")]
	public int USP_aed_Activity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Decimal(18,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActivtyId", DbType="NVarChar(50)")] string activtyId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string headingName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActivtDescp", DbType="Text")] string activtDescp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActvtImgg", DbType="NVarChar(100)")] string actvtImgg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnterBy", DbType="NVarChar(50)")] string enterBy)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, id, activtyId, headingName, activtDescp, actvtImgg, enterBy);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_aed_Press")]
	public int USP_aed_Press([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Decimal(18,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pressId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string pressDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string pressImgg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnterBy", DbType="NVarChar(50)")] string enterBy)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, id, pressId, pressDesc, pressImgg, enterBy);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_aed_Gallery")]
	public int USP_aed_Gallery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Decimal(18,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string galeryId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string galeryDescp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string galeryImgg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnterBy", DbType="NVarChar(50)")] string enterBy)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, id, galeryId, galeryDescp, galeryImgg, enterBy);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_aed_event")]
	public int USP_aed_event([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Decimal(18,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string eventId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string eventname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string eventimgg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnterBy", DbType="NVarChar(50)")] string enterBy)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, id, eventId, eventname, eventimgg, enterBy);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_adminuser")]
public partial class tbl_adminuser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Name;
	
	private string _Pwd;
	
	private string _EnterBy;
	
	private System.Nullable<System.DateTime> _EnterDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPwdChanging(string value);
    partial void OnPwdChanged();
    partial void OnEnterByChanging(string value);
    partial void OnEnterByChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    #endregion
	
	public tbl_adminuser()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pwd", DbType="NVarChar(50)")]
	public string Pwd
	{
		get
		{
			return this._Pwd;
		}
		set
		{
			if ((this._Pwd != value))
			{
				this.OnPwdChanging(value);
				this.SendPropertyChanging();
				this._Pwd = value;
				this.SendPropertyChanged("Pwd");
				this.OnPwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterBy", DbType="NVarChar(50)")]
	public string EnterBy
	{
		get
		{
			return this._EnterBy;
		}
		set
		{
			if ((this._EnterBy != value))
			{
				this.OnEnterByChanging(value);
				this.SendPropertyChanging();
				this._EnterBy = value;
				this.SendPropertyChanged("EnterBy");
				this.OnEnterByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EnterDate
	{
		get
		{
			return this._EnterDate;
		}
		set
		{
			if ((this._EnterDate != value))
			{
				this.OnEnterDateChanging(value);
				this.SendPropertyChanging();
				this._EnterDate = value;
				this.SendPropertyChanged("EnterDate");
				this.OnEnterDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Activity")]
public partial class tbl_Activity : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _ActivtyId;
	
	private string _headingName;
	
	private string _ActivtDescp;
	
	private string _ActvtImgg;
	
	private string _EnterBy;
	
	private System.Nullable<System.DateTime> _EnterDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnActivtyIdChanging(string value);
    partial void OnActivtyIdChanged();
    partial void OnheadingNameChanging(string value);
    partial void OnheadingNameChanged();
    partial void OnActivtDescpChanging(string value);
    partial void OnActivtDescpChanged();
    partial void OnActvtImggChanging(string value);
    partial void OnActvtImggChanged();
    partial void OnEnterByChanging(string value);
    partial void OnEnterByChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    #endregion
	
	public tbl_Activity()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivtyId", DbType="NVarChar(50)")]
	public string ActivtyId
	{
		get
		{
			return this._ActivtyId;
		}
		set
		{
			if ((this._ActivtyId != value))
			{
				this.OnActivtyIdChanging(value);
				this.SendPropertyChanging();
				this._ActivtyId = value;
				this.SendPropertyChanged("ActivtyId");
				this.OnActivtyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headingName", DbType="NVarChar(50)")]
	public string headingName
	{
		get
		{
			return this._headingName;
		}
		set
		{
			if ((this._headingName != value))
			{
				this.OnheadingNameChanging(value);
				this.SendPropertyChanging();
				this._headingName = value;
				this.SendPropertyChanged("headingName");
				this.OnheadingNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivtDescp", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string ActivtDescp
	{
		get
		{
			return this._ActivtDescp;
		}
		set
		{
			if ((this._ActivtDescp != value))
			{
				this.OnActivtDescpChanging(value);
				this.SendPropertyChanging();
				this._ActivtDescp = value;
				this.SendPropertyChanged("ActivtDescp");
				this.OnActivtDescpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActvtImgg", DbType="NVarChar(100)")]
	public string ActvtImgg
	{
		get
		{
			return this._ActvtImgg;
		}
		set
		{
			if ((this._ActvtImgg != value))
			{
				this.OnActvtImggChanging(value);
				this.SendPropertyChanging();
				this._ActvtImgg = value;
				this.SendPropertyChanged("ActvtImgg");
				this.OnActvtImggChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterBy", DbType="NVarChar(50)")]
	public string EnterBy
	{
		get
		{
			return this._EnterBy;
		}
		set
		{
			if ((this._EnterBy != value))
			{
				this.OnEnterByChanging(value);
				this.SendPropertyChanging();
				this._EnterBy = value;
				this.SendPropertyChanged("EnterBy");
				this.OnEnterByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EnterDate
	{
		get
		{
			return this._EnterDate;
		}
		set
		{
			if ((this._EnterDate != value))
			{
				this.OnEnterDateChanging(value);
				this.SendPropertyChanging();
				this._EnterDate = value;
				this.SendPropertyChanged("EnterDate");
				this.OnEnterDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_press")]
public partial class tbl_press : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _pressId;
	
	private string _pressDesc;
	
	private string _pressImgg;
	
	private string _EnterBy;
	
	private System.Nullable<System.DateTime> _EnterDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnpressIdChanging(string value);
    partial void OnpressIdChanged();
    partial void OnpressDescChanging(string value);
    partial void OnpressDescChanged();
    partial void OnpressImggChanging(string value);
    partial void OnpressImggChanged();
    partial void OnEnterByChanging(string value);
    partial void OnEnterByChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    #endregion
	
	public tbl_press()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pressId", DbType="NVarChar(50)")]
	public string pressId
	{
		get
		{
			return this._pressId;
		}
		set
		{
			if ((this._pressId != value))
			{
				this.OnpressIdChanging(value);
				this.SendPropertyChanging();
				this._pressId = value;
				this.SendPropertyChanged("pressId");
				this.OnpressIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pressDesc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string pressDesc
	{
		get
		{
			return this._pressDesc;
		}
		set
		{
			if ((this._pressDesc != value))
			{
				this.OnpressDescChanging(value);
				this.SendPropertyChanging();
				this._pressDesc = value;
				this.SendPropertyChanged("pressDesc");
				this.OnpressDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pressImgg", DbType="NVarChar(100)")]
	public string pressImgg
	{
		get
		{
			return this._pressImgg;
		}
		set
		{
			if ((this._pressImgg != value))
			{
				this.OnpressImggChanging(value);
				this.SendPropertyChanging();
				this._pressImgg = value;
				this.SendPropertyChanged("pressImgg");
				this.OnpressImggChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterBy", DbType="NVarChar(50)")]
	public string EnterBy
	{
		get
		{
			return this._EnterBy;
		}
		set
		{
			if ((this._EnterBy != value))
			{
				this.OnEnterByChanging(value);
				this.SendPropertyChanging();
				this._EnterBy = value;
				this.SendPropertyChanged("EnterBy");
				this.OnEnterByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EnterDate
	{
		get
		{
			return this._EnterDate;
		}
		set
		{
			if ((this._EnterDate != value))
			{
				this.OnEnterDateChanging(value);
				this.SendPropertyChanging();
				this._EnterDate = value;
				this.SendPropertyChanged("EnterDate");
				this.OnEnterDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_event")]
public partial class tbl_event : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _eventId;
	
	private string _eventname;
	
	private string _eventimgg;
	
	private string _EnterBy;
	
	private System.Nullable<System.DateTime> _EnterDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OneventIdChanging(string value);
    partial void OneventIdChanged();
    partial void OneventnameChanging(string value);
    partial void OneventnameChanged();
    partial void OneventimggChanging(string value);
    partial void OneventimggChanged();
    partial void OnEnterByChanging(string value);
    partial void OnEnterByChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    #endregion
	
	public tbl_event()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventId", DbType="NVarChar(50)")]
	public string eventId
	{
		get
		{
			return this._eventId;
		}
		set
		{
			if ((this._eventId != value))
			{
				this.OneventIdChanging(value);
				this.SendPropertyChanging();
				this._eventId = value;
				this.SendPropertyChanged("eventId");
				this.OneventIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventname", DbType="NVarChar(200)")]
	public string eventname
	{
		get
		{
			return this._eventname;
		}
		set
		{
			if ((this._eventname != value))
			{
				this.OneventnameChanging(value);
				this.SendPropertyChanging();
				this._eventname = value;
				this.SendPropertyChanged("eventname");
				this.OneventnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventimgg", DbType="NVarChar(100)")]
	public string eventimgg
	{
		get
		{
			return this._eventimgg;
		}
		set
		{
			if ((this._eventimgg != value))
			{
				this.OneventimggChanging(value);
				this.SendPropertyChanging();
				this._eventimgg = value;
				this.SendPropertyChanged("eventimgg");
				this.OneventimggChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterBy", DbType="NVarChar(50)")]
	public string EnterBy
	{
		get
		{
			return this._EnterBy;
		}
		set
		{
			if ((this._EnterBy != value))
			{
				this.OnEnterByChanging(value);
				this.SendPropertyChanging();
				this._EnterBy = value;
				this.SendPropertyChanged("EnterBy");
				this.OnEnterByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EnterDate
	{
		get
		{
			return this._EnterDate;
		}
		set
		{
			if ((this._EnterDate != value))
			{
				this.OnEnterDateChanging(value);
				this.SendPropertyChanging();
				this._EnterDate = value;
				this.SendPropertyChanged("EnterDate");
				this.OnEnterDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gallery")]
public partial class tbl_gallery : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _galeryId;
	
	private string _galeryDescp;
	
	private string _galeryImgg;
	
	private string _EnterBy;
	
	private System.Nullable<System.DateTime> _EnterDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OngaleryIdChanging(string value);
    partial void OngaleryIdChanged();
    partial void OngaleryDescpChanging(string value);
    partial void OngaleryDescpChanged();
    partial void OngaleryImggChanging(string value);
    partial void OngaleryImggChanged();
    partial void OnEnterByChanging(string value);
    partial void OnEnterByChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    #endregion
	
	public tbl_gallery()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galeryId", DbType="NVarChar(50)")]
	public string galeryId
	{
		get
		{
			return this._galeryId;
		}
		set
		{
			if ((this._galeryId != value))
			{
				this.OngaleryIdChanging(value);
				this.SendPropertyChanging();
				this._galeryId = value;
				this.SendPropertyChanged("galeryId");
				this.OngaleryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galeryDescp", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string galeryDescp
	{
		get
		{
			return this._galeryDescp;
		}
		set
		{
			if ((this._galeryDescp != value))
			{
				this.OngaleryDescpChanging(value);
				this.SendPropertyChanging();
				this._galeryDescp = value;
				this.SendPropertyChanged("galeryDescp");
				this.OngaleryDescpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galeryImgg", DbType="NVarChar(100)")]
	public string galeryImgg
	{
		get
		{
			return this._galeryImgg;
		}
		set
		{
			if ((this._galeryImgg != value))
			{
				this.OngaleryImggChanging(value);
				this.SendPropertyChanging();
				this._galeryImgg = value;
				this.SendPropertyChanged("galeryImgg");
				this.OngaleryImggChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterBy", DbType="NVarChar(50)")]
	public string EnterBy
	{
		get
		{
			return this._EnterBy;
		}
		set
		{
			if ((this._EnterBy != value))
			{
				this.OnEnterByChanging(value);
				this.SendPropertyChanging();
				this._EnterBy = value;
				this.SendPropertyChanged("EnterBy");
				this.OnEnterByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EnterDate
	{
		get
		{
			return this._EnterDate;
		}
		set
		{
			if ((this._EnterDate != value))
			{
				this.OnEnterDateChanging(value);
				this.SendPropertyChanging();
				this._EnterDate = value;
				this.SendPropertyChanged("EnterDate");
				this.OnEnterDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
